[pytest]
testpaths = .
pythonpath = .
python_files = test_*.py
python_functions = test_*
addopts = -ra -m "not integration"
filterwarnings =
    ignore::DeprecationWarning:fastapi.testclient
    ignore::starlette.exceptions.StarletteDeprecationWarning

markers =
    integration: tests that require a live database or external services
